tasks:
  - command: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py runserver
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python