# Generated by Django 3.2 on 2022-05-20 10:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='agricultureBasics',
            fields=[
                ('agriID', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='', max_length=20)),
                ('description', models.TextField(default='', max_length=1000)),
                ('publishedDateTime', models.DateTimeField(default=datetime.datetime(2022, 5, 20, 15, 39, 12, 21792))),
                ('documents', models.FileField(upload_to='AgroBasics')),
            ],
        ),
        migrations.CreateModel(
            name='agricultureSchemes',
            fields=[
                ('schemeID', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='', max_length=20)),
                ('description', models.TextField(default='', max_length=250)),
                ('startDate', models.DateTimeField(default=datetime.datetime(2022, 5, 20, 15, 39, 12, 21792))),
                ('lastDate', models.DateTimeField(default=datetime.datetime(2022, 5, 20, 15, 39, 12, 21792))),
                ('applyLink', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customerID', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(default='', max_length=100)),
                ('pincode', models.CharField(default='', max_length=6)),
                ('profileImage', models.ImageField(upload_to='Profiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('productID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='', max_length=25)),
                ('description', models.TextField(default='', max_length=100)),
                ('category', models.CharField(choices=[('Equipments', 'Equipments'), ('Pesticides', 'Pesticides')], default='"Equipments', max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('productImg', models.ImageField(upload_to='Products')),
            ],
        ),
        migrations.CreateModel(
            name='subscribers',
            fields=[
                ('subscriberID', models.BigAutoField(primary_key=True, serialize=False)),
                ('subscriberEmail', models.EmailField(default=None, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('orderID', models.CharField(default=None, max_length=10, primary_key=True, serialize=False)),
                ('contactNumber', models.TextField(default='', max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('totalPrice', models.IntegerField(default=0)),
                ('address', models.TextField(default='', max_length=250)),
                ('orderDate', models.DateField(default=datetime.date(2022, 5, 20))),
                ('expectedDeliveryDate', models.DateField(default=datetime.date(2022, 5, 20))),
                ('status', models.CharField(default='', max_length=10)),
                ('customerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.products')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('fID', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0)),
                ('opinion', models.TextField(default='', max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cartID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('customerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.customer')),
                ('productName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.products')),
            ],
        ),
        migrations.CreateModel(
            name='applications',
            fields=[
                ('applicationID', models.BigAutoField(primary_key=True, serialize=False)),
                ('appliedDate', models.DateTimeField(default=datetime.datetime(2022, 5, 20, 15, 39, 12, 21792))),
                ('applicationStatus', models.CharField(default='', max_length=20)),
                ('appliedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.customer')),
                ('appliedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.agricultureschemes')),
            ],
        ),
    ]
