# Generated by Django 3.2 on 2022-05-20 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculturebasics',
            name='publishedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 15, 39, 23, 51744)),
        ),
        migrations.AlterField(
            model_name='agricultureschemes',
            name='lastDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 15, 39, 23, 51744)),
        ),
        migrations.AlterField(
            model_name='agricultureschemes',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 15, 39, 23, 51744)),
        ),
        migrations.AlterField(
            model_name='applications',
            name='appliedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 15, 39, 23, 51744)),
        ),
    ]
