# Generated by Django 3.2 on 2022-05-29 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20220520_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='csvs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.FileField(upload_to='csvs')),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2022, 5, 29, 14, 55, 9, 824369))),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='agriculturebasics',
            name='publishedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 14, 55, 9, 822377)),
        ),
        migrations.AlterField(
            model_name='agricultureschemes',
            name='lastDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 14, 55, 9, 822377)),
        ),
        migrations.AlterField(
            model_name='agricultureschemes',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 14, 55, 9, 822377)),
        ),
        migrations.AlterField(
            model_name='applications',
            name='appliedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 14, 55, 9, 822377)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='expectedDeliveryDate',
            field=models.DateField(default=datetime.date(2022, 5, 29)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateField(default=datetime.date(2022, 5, 29)),
        ),
    ]
