# Generated by Django 3.2 on 2022-06-08 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20220529_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculturebasics',
            name='publishedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 48, 41, 202833)),
        ),
        migrations.AlterField(
            model_name='agricultureschemes',
            name='lastDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 48, 41, 202833)),
        ),
        migrations.AlterField(
            model_name='agricultureschemes',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 48, 41, 202833)),
        ),
        migrations.AlterField(
            model_name='applications',
            name='appliedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 48, 41, 202833)),
        ),
        migrations.AlterField(
            model_name='csvs',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 14, 48, 41, 202833)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='expectedDeliveryDate',
            field=models.DateField(default=datetime.date(2022, 6, 8)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateField(default=datetime.date(2022, 6, 8)),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Equipments', 'Equipments'), ('Fertilizers', 'Fertilizers')], default='"Equipments', max_length=20),
        ),
    ]
