# Generated by Django 3.2 on 2022-06-24 09:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0004_auto_20220608_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='grassCutters',
            fields=[
                ('grassCutterID', models.BigAutoField(primary_key=True, serialize=False)),
                ('city', models.TextField(default='', max_length=20)),
                ('profilePicture', models.ImageField(upload_to='Grass_Cutters')),
                ('price', models.IntegerField(default=0)),
                ('userObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='csvs',
        ),
        migrations.AlterField(
            model_name='agriculturebasics',
            name='publishedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 14, 58, 1, 146294)),
        ),
        migrations.AlterField(
            model_name='agricultureschemes',
            name='lastDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 14, 58, 1, 146294)),
        ),
        migrations.AlterField(
            model_name='agricultureschemes',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 14, 58, 1, 146294)),
        ),
        migrations.AlterField(
            model_name='applications',
            name='appliedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 14, 58, 1, 146294)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='expectedDeliveryDate',
            field=models.DateField(default=datetime.date(2022, 6, 24)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateField(default=datetime.date(2022, 6, 24)),
        ),
    ]
