# Generated by Django 3.2 on 2022-06-24 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20220624_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grasscutters',
            name='profilePicture',
        ),
        migrations.AddField(
            model_name='grasscutters',
            name='district',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='agriculturebasics',
            name='publishedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 15, 8, 57, 914286)),
        ),
        migrations.AlterField(
            model_name='agricultureschemes',
            name='lastDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 15, 8, 57, 914286)),
        ),
        migrations.AlterField(
            model_name='agricultureschemes',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 15, 8, 57, 914286)),
        ),
        migrations.AlterField(
            model_name='applications',
            name='appliedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 15, 8, 57, 914286)),
        ),
    ]
