# Generated by Django 4.2 on 2023-04-16 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0008_customer_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jobID', models.BigAutoField(primary_key=True, serialize=False)),
                ('pincode', models.CharField(default='', max_length=6)),
                ('salary', models.IntegerField(default=350)),
                ('workforce', models.IntegerField(default=10)),
                ('jobType', models.TextField(default='', max_length=200)),
                ('userObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
