# Generated by Django 4.2 on 2023-04-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hours',
            field=models.IntegerField(default=10),
        ),
    ]
